package com.yandex.lavka.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    COURIER_NOT_FOUND,
    ORDER_NOT_FOUND,
    ORDER_ALREADY_COMPLETED,
    COURIER_ORDER_MISMATCH,
    INVALID_TIME_FORMAT,
    REGION_NOT_SUPPORTED,
    INVALID_JSON,
    DATABASE_CONSTRAINT_VIOLATION,
    INTERNAL_ERROR
}
